CREATE TABLE IF NOT EXISTS films
(
    id           INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name         varchar(40) NOT NULL,
    description  varchar(200),
    release_data varchar(40),
    duration     INTEGER,
    mpa_id       INTEGER,
    CONSTRAINT FILMS_PK PRIMARY KEY (id)
    );



CREATE TABLE IF NOT EXISTS users
(
    id       INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    email    varchar(40) NOT NULL,
    login    varchar(20) NOT NULL,
    name     varchar(20),
    birthday varchar(10),
    CONSTRAINT USERS_PK PRIMARY KEY (id)
    );

CREATE TABLE IF NOT EXISTS film_genre
(
    film_id  INTEGER,
    genre_id INTEGER,
    CONSTRAINT film_genre_PK PRIMARY KEY (film_id, genre_id)
    );



CREATE TABLE IF NOT EXISTS genre
(
    id   INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name varchar(20) NOT NULL,
    CONSTRAINT genre_PK PRIMARY KEY (id)
    );

CREATE TABLE IF NOT EXISTS mpa
(
    id   INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name varchar(20) NOT NULL,
    CONSTRAINT mpa_PK PRIMARY KEY (id)
    );

CREATE TABLE IF NOT EXISTS likes
(
    film_id INTEGER,
    user_id INTEGER,
    CONSTRAINT likes_PK PRIMARY KEY (film_id, user_id)
    );



CREATE TABLE IF NOT EXISTS friends
(
    user_id   INTEGER,
    friend_id INTEGER,
    CONSTRAINT friends_PK PRIMARY KEY (user_id, friend_id)
    );
